services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    command: pnpm dev
